version: "3.7"
services:
  db:
    image: postgres:10.15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --no-locale"
      LANG: ja_JP.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
